import { Link, useParams } from 'react-router-dom';
import { useLiveQuery } from 'dexie-react-hooks';
import { db } from '../db/database';
import { formatMoney } from '../domain/money';
import { formatDate } from '../domain/display';
import { matchMortgageInstallments, mortgageProgress } from '../domain/mortgage-matching';
import PageHeader from '../components/PageHeader';

export default function LiabilityDetailPage() {
  const { liabilityId } = useParams();
  const liability = useLiveQuery(() => liabilityId ? db.liabilities.get(liabilityId) : undefined, [liabilityId]);
  const transactions = useLiveQuery(() => db.transactions.toArray(), []);
  if (liability === undefined) return <p role="status" className="rounded-2xl border border-line bg-surface p-6 text-sm text-muted">Caricamento passività…</p>;
  if (!liability) return <section><PageHeader title="Passività non trovata" description="Il debito richiesto non è disponibile." /><Link to="/liabilities" className="text-green">Torna alle passività</Link></section>;
  const plan = liability.mortgage;
  const matches = plan ? matchMortgageInstallments(plan, transactions ?? []) : [];
  const matched = new Set(matches.map((item) => item.installment.number));
  const progress = plan ? mortgageProgress(plan, matches) : undefined;
  const planPaid = progress?.paidCount ?? 0;
  const residual = progress?.current?.residualCents ?? liability.amountCents;
  const next = progress?.next;
  return <section className="min-w-0"><PageHeader title={liability.name} description="Dettaglio completo del finanziamento e del piano di ammortamento." /><div className="mb-5 flex flex-wrap gap-2"><Link to="/liabilities" className="inline-flex min-h-11 items-center rounded-xl border border-line px-4 text-sm font-semibold text-ink">Torna alle passività</Link></div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Capitale residuo', formatMoney(-residual)], ['Rate pagate', `${progress?.paidCount ?? 0} / ${plan?.installments.length ?? '—'}`], ['Rate residue', progress ? String(progress.remaining) : '—'], ['Prossima rata', next ? `${formatDate(next.dueDate)} · ${formatMoney(-next.installmentCents)}` : '—']].map(([label, value]) => <article key={label} className="rounded-2xl border border-line bg-surface p-4 shadow-card"><p className="text-sm text-muted">{label}</p><p className="mt-2 text-xl font-bold tabular-nums text-ink">{value}</p></article>)}</section>
    <section className="mt-5 rounded-2xl border border-line bg-surface p-4 sm:p-5"><h2 className="text-lg font-semibold">Informazioni finanziamento</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-3"><div><dt className="text-muted">Importo iniziale</dt><dd className="font-semibold">{plan?.originalAmountCents ? formatMoney(plan.originalAmountCents) : 'Non indicato'}</dd></div><div><dt className="text-muted">Debito residuo contrattuale</dt><dd className="font-semibold">{plan?.debtResidualCents ? formatMoney(plan.debtResidualCents) : 'Non indicato'}</dd></div><div><dt className="text-muted">Data aggiornamento</dt><dd className="font-semibold">{formatDate(liability.asOf)}</dd></div><div><dt className="text-muted">Conto addebito</dt><dd className="font-semibold">{plan?.accountLabel ?? 'Non indicato'}</dd></div><div><dt className="text-muted">Rata prevista</dt><dd className="font-semibold">{next ? formatMoney(-next.installmentCents) : '—'}</dd></div><div><dt className="text-muted">Interessi prossima rata</dt><dd className="font-semibold">{next ? formatMoney(-next.interestCents) : '—'}</dd></div></dl><p className="mt-4 rounded-xl bg-canvas p-3 text-sm text-muted">TAN e TAEG non sono presenti nelle colonne del piano importato. Potranno essere aggiunti manualmente nella scheda del finanziamento.</p></section>
    {plan ? <section className="mt-5 overflow-hidden rounded-2xl border border-line bg-surface"><div className="border-b border-line p-4 sm:p-5"><h2 className="text-lg font-semibold">Piano di ammortamento</h2><p className="mt-1 text-sm text-muted">{plan.scheduleFileName} · {planPaid} rate pagate nel piano · {matches.length} movimenti abbinati all’import.</p></div><div className="max-h-[65dvh] overflow-auto"><table className="w-full min-w-[760px] text-sm"><thead className="sticky top-0 bg-canvas text-left text-muted"><tr><th className="px-3 py-3">Rata</th><th className="px-3 py-3">Scadenza</th><th className="px-3 py-3">Stato</th><th className="px-3 py-3 text-right">Capitale</th><th className="px-3 py-3 text-right">Interessi</th><th className="px-3 py-3 text-right">Rata</th><th className="px-3 py-3 text-right">Residuo</th></tr></thead><tbody className="divide-y divide-line">{plan.installments.map((item) => <tr key={item.number} className={matched.has(item.number) ? 'bg-green-soft/40' : ''}><th className="px-3 py-2 text-left font-medium">{item.number}</th><td className="px-3 py-2">{formatDate(item.dueDate)}</td><td className="px-3 py-2">{matched.has(item.number) ? 'Movimento abbinato' : item.status === 'paid' ? 'Pagata nel piano' : item.status === 'due' ? 'Da pagare' : '—'}</td><td className="px-3 py-2 text-right tabular-nums">{formatMoney(-item.principalCents)}</td><td className="px-3 py-2 text-right tabular-nums">{formatMoney(-item.interestCents)}</td><td className="px-3 py-2 text-right tabular-nums">{formatMoney(-item.installmentCents)}</td><td className="px-3 py-2 text-right tabular-nums">{formatMoney(-item.residualCents)}</td></tr>)}</tbody></table></div></section> : <section className="mt-5 rounded-2xl border border-dashed border-line p-6 text-sm text-muted">Nessun piano di ammortamento collegato.</section>}
  </section>;
}
